@startuml
start

:Initialize ADC (sen_hal);
:Setup database (sens_db);

fork
  :Start data collection thread;
  while (data collection continues) is (yes)
    :Collect sensor data in loop;
    :Store data in database (sens_db);
  endwhile (no)
  :Stop data collection thread;
fork again
  :Start web posting thread;
  while (web posting continues?) is (yes)
    :Read Sensor data from database (sens_db);
    :Post sensor data to web (sen_web.post_sensor_data);
   endwhile (no)
  :Stop web posting thread;
end fork

:Stop threads on interrupt;
:Close database connection;

stop
@enduml