@startuml
participant Main
participant sen_hal
participant Adafruit_ADS1x15

Main -> sen_hal: adc_init()
activate sen_hal
sen_hal -> Adafruit_ADS1x15: Create ADS1115 ADC instance
activate Adafruit_ADS1x15
return ADC instance
deactivate Adafruit_ADS1x15
deactivate sen_hal

Main -> sen_hal: read_current(device_id)
activate sen_hal
sen_hal -> Adafruit_ADS1x15: read_adc(device_id, gain=GAIN) (10 times)
activate Adafruit_ADS1x15
return raw_value (10 times)
sen_hal -> sen_hal: Calculate max(raw_value) - ADC_CALIBRATION
sen_hal -> sen_hal: Ensure raw_value >= ADC_RESOLUTION / 2
sen_hal -> sen_hal: Convert raw_value to voltage
sen_hal -> sen_hal: Calculate current in Amperes
return current
deactivate Adafruit_ADS1x15
deactivate sen_hal
@enduml